### ISSUE TITLE
Se på innrykk for ol og ul innenfor ol og ul (i Nettleserbok)

### ISSUE THREAD

**Issue by GauteR** [nlbdev/nlb-scss#16]
```scss
    ol, ul {
        padding-inline-start: 0;
        margin-left: 45px;

        @include media-breakpoint-only('sm') {
            margin-bottom: $nlb-p-margin-bottom-sm*0.75;
        }
    
        @include media-breakpoint-only('md') {
            margin-bottom: $nlb-p-margin-bottom-md*0.75;
        }
    
        @include media-breakpoint-up('lg') {
            margin-bottom: $nlb-p-margin-bottom-lg*0.75;
        }

        li {
            margin-left: 0;
            margin-bottom: 8px;
            @include media-breakpoint-only('sm') {
                margin-bottom: 10px;
            }
            @include media-breakpoint-up('md') {
                margin-bottom: 12px;
            }
            
            ol, ul {
                margin-left: 30px !important;
            }
        }

        &.plain {
            list-style-type: none;
        }
    }
```

Kunne vært benyttet i nettleserbok fremfor gjeldende: https://github.com/nlbdev/nlb-scss/blob/e494e7befd8f72da820d78176c9bb7b08a1fa316/src/scss/_core.scss#L366
